#!/bin/sh /etc/rc.common
# Example script  
# Copyright (C) 2008 OpenWrt.org  
   
START=124

start() {          
          echo "autotest start!"
          /usr/bin/autotest -t -d -p -w -l -r
}                   
   
