#!/bin/sh

change_default_network() {
	local distname=$1

	case $distname in
		EZR13)
			local ret=$(uci -q get network.MOBILE)
			[ "$ret" == "interface" ] && {
				uci delete network.MOBILE
				uci set network.lan.ifname=eth0
				uci set network.lan.ipaddr="192.168.10.1"
				uci set network.wan.ifname=eth1
				uci delete mwan3.MOBILE
				uci delete mwan3.MOBILE_m
				uci delete mwan3.4G_only
				uci delete mwan3.ALL
				uci set system.@system[0].hostname=OutdoorExtender
				uci commit system
				uci commit network
				uci commit mwan3
			}
			;;
		EZR23)
			local firstboot=$(uci -q get system.@system[0].firstboot)
			[ -z "$firstboot" ] && {
				uci set network.lan.ipaddr="192.168.20.1"
				uci set system.@system[0].hostname=CellularRouter
				uci set system.@system[0].firstboot=1
				uci commit network
				uci commit system
			}
			;;
	esac
	
	local proto=$(uci -q get network.MOBILE.proto)
	[ "$proto" == "qmi" -o "$proto" == "3g" ] && {
		uci set network.MOBILE.proto="modemmanager"
		uci set network.MOBILE.device=""
		uci commit network
	}
}

fix_sim_config() {
	local dist=$1
	local apn apn1 apn2 simno simnum
	local auth username password pincode 
	local service dialnumber

	simnum=$(uci -q get productinfo.hardware.simcard_num)

	[ "$simnum" -ge 2 ] || return

	apn=$(uci -q get network.MOBILE.apn)
	[ -n "$apn" ] || return

	apn1=$(uci -q get network.MOBILE.apn1)
	apn2=$(uci -q get network.MOBILE.apn2)

	[ -z "$apn1" ] && [ -z "$apn2" ] && {
		simno=$(uci -q get network.MOBILE.sim)
		if [ "$simno" == 1 ]; then
			auth=$(uci -q get network.MOBILE.auth)
			username=$(uci -q get network.MOBILE.username)
			password=$(uci -q get network.MOBILE.password)
			pincode=$(uci -q get network.MOBILE.pincode)
			service=$(uci -q get network.MOBILE.service)
			dialnumber=$(uci -q get network.MOBILE.dialnumber)

			uci set network.MOBILE.apn2=$apn
			[ -n "$auth" ] && uci set network.MOBILE.auth2=$auth
			[ -n "$username" ] && uci set network.MOBILE.username2=$username
			[ -n "$password" ] && uci set network.MOBILE.password2=$password
			[ -n "$pincode" ] && uci set network.MOBILE.pincode2=$pincode
			[ -n "$service" ] && uci set network.MOBILE.service2=$service
			[ -n "$dialnumber" ] && uci set network.MOBILE.dialnumber2=$dialnumber
		else
			auth=$(uci -q get network.MOBILE.auth)
			username=$(uci -q get network.MOBILE.username)
			password=$(uci -q get network.MOBILE.password)
			pincode=$(uci -q get network.MOBILE.pincode)
			service=$(uci -q get network.MOBILE.service)
			dialnumber=$(uci -q get network.MOBILE.dialnumber)
			
			uci set network.MOBILE.apn1=$apn
			[ -n "$auth" ] && uci set network.MOBILE.auth1=$auth
			[ -n "$username" ] && uci set network.MOBILE.username1=$username
			[ -n "$password" ] && uci set network.MOBILE.password1=$password
			[ -n "$pincode" ] && uci set network.MOBILE.pincode1=$pincode
			[ -n "$service" ] && uci set network.MOBILE.service1=$service
			[ -n "$dialnumber" ] && uci set network.MOBILE.dialnumber1=$dialnumber
		fi

		uci commit network
	}
}


distname=$(grep DISTRIB_ID /etc/openwrt_release | awk -F= '{print $2}' | sed s/\'//g)

serial_number=$(fw_printenv serial_number|awk -F= '{print $2}')

[ "y$serial_number" == "y" ] && {
	local mac=$(ip link show eth0 | grep ether | awk '{ print $2 }' | sed s/\://g)
	local random=$(head -n 10 /dev/urandom | md5sum )
	random=$(echo ${random:0:4})
	serial_number=ES${random}${mac:8:12}
	serial_number=$(echo $serial_number | tr 'a-z' 'A-Z')
	fw_setenv serial_number $serial_number
}

uci set productinfo.hardware.serial_number=$serial_number
uci set productinfo.hardware.product_name=$distname
uci commit productinfo


change_default_network "$distname"
fix_sim_config "$distname"

exit 0
