#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frpc[-1]
	add ucitrack frpc
	set ucitrack.@frpc[-1].init=frpc
	commit ucitrack
EOF

frpc=$(uci -q get frpc.@frpc[-1])

if [ -z "$frpc" ]; then
	uci -q add frpc frpc
fi

if [ "x$frpc" != "xmain" ]; then
	uci -q batch <<-EOF >/dev/null
		rename frpc.@frpc[-1]="main"
		commit frpc
	EOF
fi

serial_number=$(uci get productinfo.hardware.serial_number)
[ -n "$serial_number" ] && uci set frpc.outdoorweb.subdomain=$serial_number && uci commit frpc

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
